version: '3.3'
services:
  twofactor_mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'twofactor'
      MYSQL_USER: 'twofactor'
      MYSQL_PASSWORD: 'twofactor'
      MYSQL_ROOT_PASSWORD: 'twofactor'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - twofactor_mysql:/var/lib/mysql
      
volumes:
  twofactor_mysql: